### ISSUE TITLE
'The official ScyllaDB Driver ' - what makes it official?

### ISSUE THREAD

**Issue by mykaul** [expressots/scylladb-driver#8]
Hi,

Reading your project's documentation, it's unclear to me what makes it the official driver for ScyllaDB?

**Comment by rsaz** [comment]
Hi @mykaul I have no idea who you are, however, instead of publicly discussing  this topic you can send me an email (that is already publically available) introducing yourself in a way I can validate, then we can engage in conversation so that I can explain you the idea of this repo and who is behind.
I'll be more than happy to do so, as long as you prove your relationship with Scylla DB, then I am ok with it. :)

Here is the email: richard.zampieri@expresso-ts.com

**Comment by rsaz** [comment]
> Hi,
> 
> Reading your project's documentation, it's unclear to me what makes it the official driver for ScyllaDB?

Hi @mykaul I have no idea who you are, however, instead of publicly discussing  this topic you can send me an email (that is already publically available) introducing yourself, then we can engage in conversation so that I can explain you the idea of this repo and who is behind.
I'll be more than happy to do so, as long as you prove your relationship with Scylla DB, then I am ok with it. :)

Here is the email: richard.zampieri@expresso-ts.com

I changed the wording in the repo because indeed we are not official. All repos in ExpressoTS are under MIT LICENSE.

This repo is still in development!

**Comment by mykaul** [comment]
Thanks Richard. No worries - I'm comfortable with this being in the public. I'm ScyllaDB's VP R&D, and while I'm very happy to see this project (and I'll keep an eye on its releases from now on), I wanted to clarify the 'official' statement. I see that it was already changed - so all good.

As for the license - https://github.com/expressots/scylladb-driver/community still doesn't show the license. 

Thanks again for making this code open source!
